Repository sparcityeu/sparsebase, pull requests merged in 2022-11, with the labels that each got.

#232 Installation Tests
  .github/workflows/testing.yml
  src/CMakeLists.txt
Labels: priority: now, state: pending, type: testing

#231 AMD reordering and reorder heatmaps
  .github/workflows/testing.yml
  CMakeLists.txt
  docs/conf.py
  docs/pages/getting_started/available.md
  docs/pages/how_to_guides/how_add_reordering.md
  src/CMakeLists.txt
  src/generate_explicit_instantiations.py
  src/sparsebase/config.h.in
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/exception.h
  src/sparsebase/utils/utils.h
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: type: feature

#230 Pulp & Patoh Integration
  .github/workflows/testing.yml
  CMakeLists.txt
  docs/conf.py
  docs/pages/contributing/documentation_guide.md
  docs/pages/getting_started/available.md
  docs/pages/getting_started/optional_dependencies.md
  src/CMakeLists.txt
  src/generate_explicit_instantiations.py
  src/sparsebase/config.h.in
  src/sparsebase/experiment/experiment.h
  src/sparsebase/feature/feature.h
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.h
  src/sparsebase/utils/exception.h
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: priority: soon, state: review needed, type: feature
