Repository sparcityeu/sparsebase, pull requests merged in 2022-09, with the labels that each got.

#138 Added `make` step in testing getting started
  docs/pages/getting_started.md
Labels: type: bug, priority: now, state: review needed

#128 Matrix market updates: header parsing, symmetric reading, array format, and automatic weightedness
  examples/csr_coo/csr_coo.cc
  examples/sparse_feature/sparse_feature.cc
  examples/sparse_reader/sparse_reader.cc
  src/sparsebase/object/object.cc
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/io/reader.cc
  src/sparsebase/utils/io/reader.h
  tests/suites/sparsebase/format/format_tests.cc
  tests/suites/sparsebase/utils/io/reader_tests.cc
Labels: state: review needed, type: fix

#142 Adding ReorderBase and GraphFeauresBase + easy convert function + Transform rework
  docs/pages/getting_started.md
  docs/pages/how_to_guides/how_add_reordering.md
  docs/pages/tutorials/001_reordering.md
  examples/CMakeLists.txt
  examples/array_example/array_example.cu
  examples/custom_order/custom_order.cc
  examples/degree_order/degree_order.cc
  examples/format_conversion/format_conversion.cc
  examples/linear_solver/CMakeLists.txt
  examples/linear_solver/linear_solver.cc
  src/generate_explicit_instantiations.py
  src/sparsebase/format/cuda/format.cuh
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/converter.h
  tests/suites/sparsebase/format/format_tests.cc
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: state: review needed, type: feature

#146 FunctionMatcherMixin conversion trigger
  examples/custom_order/custom_order.cc
  examples/degree_order/degree_order.cc
  examples/linear_solver/linear_solver.cc
  examples/rcm_order/rcm_order.cc
  examples/sparse_feature/sparse_feature.cc
  src/sparsebase/feature/feature.cc
  src/sparsebase/feature/feature.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/exception.h
  tests/suites/sparsebase/feature/feature_tests.cc
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: state: review needed, type: feature

#153 Metis Integration and Optional Libraries
  CMakeLists.txt
  examples/CMakeLists.txt
  examples/metis_partition/CMakeLists.txt
  examples/metis_partition/metis_partition.cc
  src/CMakeLists.txt
  src/generate_explicit_instantiations.py
  src/sparsebase/config.h.in
  src/sparsebase/format/cuda/format.cu
  src/sparsebase/preprocess/cuda/preprocess.cu
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/cuda/converter.cu
  src/sparsebase/utils/exception.h
  src/sparsebase/utils/io/reader.cc
Labels: priority: now, state: approved, type: feature
