Repository sparcityeu/sparsebase, pull requests merged in 2022-10, with the labels that each got.

#186 Changes to As<>() function in Format and a new Is<>() function
  src/sparsebase/format/format.h
  tests/suites/sparsebase/format/format_tests.cc
Labels: priority: soon, state: review needed, type: feature

#190 Fixed CUDA compilation and added auto architecture detection
  CMakeLists.txt
  docs/pages/contributing/testing_guide.md
  docs/pages/getting_started.md
  docs/pages/how_to_guides/how_add_reordering.md
  examples/CMakeLists.txt
  examples/array_example/array_example.cu
  examples/cuda_example/cuda_example.cu
  src/CMakeLists.txt
  src/generate_explicit_instantiations.py
  src/sparsebase/config.h.in
  src/sparsebase/context/cuda/context.cu
  src/sparsebase/context/cuda/context.cuh
  src/sparsebase/format/cuda/format.cuh
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/sparsebase.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/converter.h
  tests/suites/sparsebase/preprocess/cuda/CMakeLists.txt
  tests/suites/sparsebase/preprocess/cuda/preprocess_tests.cu
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: priority: now, state: approved, type: fix

#179 Docs/dependency docs
  docs/index.rst
  docs/pages/contributing/dependencies.md
  docs/pages/contributing/instantiations.md
  docs/pages/getting_started/index.rst
  docs/pages/getting_started/installation_building.md
  docs/pages/getting_started/optional_dependencies.md
  docs/pages/getting_started/usage.md
  docs/requirements.txt
Labels: type: docs, state: approved

#189 Demangling Utilities
  src/CMakeLists.txt
  src/sparsebase/format/format.cc
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/exception.h
  src/sparsebase/utils/utils.cc
  src/sparsebase/utils/utils.h
  tests/suites/sparsebase/format/format_tests.cc
Labels: state: approved, type: feature

#191 Removed square brackets from uniq_ptr to introduce `void` as ValueType again
  CMakeLists.txt
  docs/pages/getting_started/usage.md
  src/generate_explicit_instantiations.py
  src/sparsebase/format/cuda/format.cu
  src/sparsebase/format/format.cc
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/cuda/converter.cu
  src/sparsebase/utils/io/reader.cc
  src/sparsebase/utils/io/sparse_file_format.h
  src/sparsebase/utils/io/writer.cc
  tests/suites/sparsebase/format/format_tests.cc
Labels: state: review needed, type: fix

#124 Feature/grayreordering
  src/generate_explicit_instantiations.py
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: state: approved, type: feature

#194 Cross-type conversion, cached base functions, Contexts mutable once, casting FormatOrderX without templates, casting `Permute` outputs is optional
  docs/pages/contributing/instantiations.md
  docs/pages/getting_started/usage.md
  docs/pages/how_to_guides/how_add_reordering.md
  docs/pages/tutorials/001_reordering.md
  examples/custom_format/custom_format.cc
  examples/custom_order/custom_order.cc
  examples/degree_order/degree_order.cc
  examples/linear_solver/linear_solver.cc
  examples/rcm_order/rcm_order.cc
  examples/sparse_reader/sparse_reader.cc
  src/generate_explicit_instantiations.py
  src/sparsebase/format/format.cc
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/converter.h
  src/sparsebase/utils/converter/cuda/converter.cu
  src/sparsebase/utils/exception.h
  src/sparsebase/utils/utils.h
  tests/suites/sparsebase/format/format_tests.cc
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
  tests/suites/sparsebase/utils/converter/converter_tests.cc
Labels: type: feature, type: fix

#207 Mac Testing Action Fix
  .github/workflows/testing.yml
Labels: priority: now, state: review needed, type: fix, type: testing

#211 Mac Action Compiler Change
  .github/workflows/testing.yml
Labels: priority: now, state: review needed, type: testing

#210 Logger
  src/sparsebase/format/format.cc
  src/sparsebase/utils/utils.cc
  src/sparsebase/utils/utils.h
Labels: priority: soon, state: pending, type: feature

#212 Getting Started Update
  docs/pages/getting_started/installation_building.md
  docs/pages/getting_started/optional_dependencies.md
  docs/pages/getting_started/usage.md
Labels: type: docs, priority: soon, state: approved

#206 Multi-step conversion + documentation changes + bug fixes + small code changes
  docs/pages/getting_started/usage.md
  docs/pages/how_to_guides/how_add_reordering.md
  docs/pages/how_to_guides/res/optimal_reorder_cudacsr.png
  docs/pages/tutorials/001_reordering.md
  docs/pages/tutorials/003_cuda_spmv.md
  docs/pages/tutorials/res/rcm_reorder_cudacsr.png
  examples/custom_converter/custom_converter.cc
  examples/custom_format/custom_format.cc
  examples/metis_partition/metis_partition.cc
  src/CMakeLists.txt
  src/sparsebase/format/format.h
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/converter.h
  src/sparsebase/utils/converter/cuda/converter.cu
  src/sparsebase/utils/io/iobase.h
  src/sparsebase/utils/utils.h
  tests/CMakeLists.txt
  tests/suites/sparsebase/preprocess/cuda/preprocess_tests.cu
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
  tests/suites/sparsebase/utils/converter/converter_tests.cc
  tests/suites/sparsebase/utils/converter/cuda/CMakeLists.txt
  tests/suites/sparsebase/utils/converter/cuda/converter_tests.cu
  tutorials/001_reordering/solved/solved.cc
  tutorials/001_reordering/start_here/tutorial_001.cc
  tutorials/003_cuda_spmv/solved/solved.cu
  tutorials/003_cuda_spmv/start_here/tutorial_003.cu
Labels: type: docs, priority: now, state: review needed, type: feature, type: fix

#217 Metis Reorder Integration
  examples/metis_partition/metis_partition.cc
  src/generate_explicit_instantiations.py
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
Labels: state: approved, type: feature

#221 Formatted using Google's style
  .clang-format
  .format.bash
  .github/workflows/testing.yml
  examples/array_example/array_example.cu
  examples/cuda_example/cuda_example.cu
  examples/custom_converter/custom_converter.cc
  examples/custom_format/custom_format.cc
  examples/custom_order/custom_order.cc
  examples/degree_distribution/degree_distribution.cc
  examples/degree_order/degree_order.cc
  examples/format_conversion/format_conversion.cc
  examples/linear_solver/linear_solver.cc
  examples/metis_partition/metis_partition.cc
  examples/sparse_feature/sparse_feature.cc
  src/sparsebase/context/context.cc
  src/sparsebase/context/context.h
  src/sparsebase/context/cuda/context.cu
  src/sparsebase/context/cuda/context.cuh
  src/sparsebase/feature/feature.cc
  src/sparsebase/feature/feature.h
  src/sparsebase/format/cuda/format.cu
  src/sparsebase/format/cuda/format.cuh
  src/sparsebase/format/format.cc
  src/sparsebase/format/format.h
  src/sparsebase/object/object.cc
  src/sparsebase/object/object.h
  src/sparsebase/preprocess/cuda/preprocess.cu
  src/sparsebase/preprocess/cuda/preprocess.cuh
  src/sparsebase/preprocess/preprocess.cc
  src/sparsebase/preprocess/preprocess.h
  src/sparsebase/sparsebase.h
  src/sparsebase/utils/converter/converter.cc
  src/sparsebase/utils/converter/converter.h
  src/sparsebase/utils/converter/cuda/converter.cu
  src/sparsebase/utils/converter/cuda/converter.cuh
  src/sparsebase/utils/exception.h
  src/sparsebase/utils/io/iobase.h
  src/sparsebase/utils/io/reader.cc
  src/sparsebase/utils/io/reader.h
  src/sparsebase/utils/io/sparse_file_format.h
  src/sparsebase/utils/io/writer.cc
  src/sparsebase/utils/io/writer.h
  src/sparsebase/utils/utils.cc
  src/sparsebase/utils/utils.h
  tests/suites/sparsebase/feature/feature_tests.cc
  tests/suites/sparsebase/format/format_tests.cc
  tests/suites/sparsebase/preprocess/cuda/preprocess_tests.cu
  tests/suites/sparsebase/preprocess/preprocess_tests.cc
  tests/suites/sparsebase/utils/converter/converter_tests.cc
  tests/suites/sparsebase/utils/converter/cuda/converter_tests.cu
  tests/suites/sparsebase/utils/io/reader_tests.cc
  tests/suites/sparsebase/utils/io/writer_tests.cc
Labels: type: chore

#201 Feature/experiment
  CMakeLists.txt
  docs/pages/tutorials/003_experiment.md
  docs/pages/tutorials/004_cuda_spmv.md
  examples/CMakeLists.txt
  examples/custom_experiment/CMakeLists.txt
  examples/custom_experiment/custom_experiment.cc
  examples/example_experiment/CMakeLists.txt
  examples/example_experiment/example_experiment.cu
  src/CMakeLists.txt
  src/sparsebase/experiment/experiment.cc
  src/sparsebase/experiment/experiment.h
  src/sparsebase/sparsebase.h
  tests/CMakeLists.txt
  tests/suites/sparsebase/experiment/CMakeLists.txt
  tests/suites/sparsebase/experiment/experiment_tests.cc
  tests/suites/sparsebase/feature/CMakeLists.txt
  tutorials/003_experiment/solved/solved.cc
  tutorials/003_experiment/start_here/tutorial_003.cc
  tutorials/004_cuda_spmv/solved/solved.cu
  tutorials/004_cuda_spmv/start_here/tutorial_004.cu
Labels: priority: now, type: feature
